name: news_app_demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  retrofit: ^4.9.1
  logger: ^2.6.0  # for logging purpose
  json_annotation: ^4.9.0
  dio: ^5.9.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  retrofit_generator: ^10.0.1
  build_runner: ^2.6.0
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true
