name: news_app_demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  dio: ^5.9.0
  retrofit: 4.6.0
  json_annotation: ^4.9.0
  get_it: ^9.2.0
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  retrofit_generator: ^9.7.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
flutter:
  uses-material-design: true
